este es un arreglo para pull request
Munachi-mc/Prueba5 pull request #1
Opened 2020-09-01 19:30 UTC by Munachi-mc

No devimos pasar este error a master

2020-09-01 19:37 UTC, Momentos-Dulces reviewed
La verdad no como arreglarlo

2020-09-02 19:07 UTC, Munachi-mc commented
Intentalo por favor

2020-09-02 19:19 UTC, anita-huerfanita requested changes
Has algun cambio en el encabezado!!

2020-09-02 19:35 UTC, Munachi-mc commented
cambio hechos haslo el merge por favor

2020-09-02 19:38 UTC, anita-huerfanita approved these changes
Excelente!! eso te pedia cabeza hueca >)

2020-09-02 19:41 UTC, merged